title: Welsh land and property data landscape
relative_links:
  enabled: true
  collections: false
  include:
    - index.md
    - documents.md
    - geospatial.md
    - identifiers.md
    - temporal.md
    - use.md
    - examples/*.pdf
    - examples/*.geojson
