title: Welsh land and property data landscape
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
  include:
    - index.md
    - examples/*.pdf
    - examples/*.geojson
  exclude:
    - README.md
    - todo.txt
